name: Docker Image CI

on:
  push:
    branches: ["ci-cd-with-actions"]
  # pull_request:
  # branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install ssh
        run: sudo apt-get install openssh-client

      - name: Add SSH key to agent
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install dvc
        run: pip install dvc

      - name: Install dvc-ssh
        run: pip install dvc-ssh

      - name: Pull dvc data
        run: dvc pull data/data.csv.dvc

      - name: Pull dvc all_embeddings
        run: dvc pull data/all_embeddings.npy.dvc

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # - name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/art-guide-tg-bot:latest
