name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install ssh
        run: sudo apt-get install openssh-client

      - name: Add SSH key to agent
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install dvc dvc-ssh

      - name: Pull dvc data
        run: dvc pull data/data.csv

      - name: Pull dvc all_embeddings
        run: dvc pull data/all_embeddings.npy

      - name: Build the Docker image
        run: docker build . --tag ${{ secrets.DOCKERHUB_USERNAME }}/art-guide-tg-bot:latest

      - name: Docker hub login
        run: docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN}}

      - name: Docker push
        run: docker push arielxx/art-guide-tg-bot:latest

  # missing deploy job
